apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-service
spec:
  replicas: 3
  selector:
    name: kube-hello
  template:
    metadata:
      labels:
        name: kube-hello
    spec:
      containers:
      - image: tutum/hello-world
        name: tutum-hello
        ports:
          - containerPort: 80
